
### 1. 회원가입 - 방장
POST http://localhost:8080/api/members/register
Content-Type: application/json

{
  "provider": "LOCAL",
  "providerId": "del-host-02",
  "nickname": "삭제테스트방장1",
  "password": "password1234"
}

> {%
    client.global.set("hostMemberId", response.body.id);
%}



### 2. 로그인 - 방장
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "providerId": "del-host-02",
  "password": "password1234"
}

> {%
    client.global.set("hostToken", response.body.token);
    client.global.set("refreshToken", response.body.refreshToken);
%}

### 토큰 재할당(refreshtoken, accesstoken)
POST http://localhost:8080/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "10dea4eb-f85e-4df2-8ad2-ad9ccefe5e5a"
}

> {%
    client.global.set("hostToken", response.body.token);
    client.global.set("refreshToken", response.body.refreshToken);
%}


###3.회원탈티
DELETE http://localhost:8080/api/members/delete-account
Content-Type: application/json
Authorization: Bearer {{hostToken}}

{
    "password": "password1234"
}


### 마이페이지
GET http://localhost:8080/api/members/mypage
Content-Type: application/json
Authorization: Bearer {{hostToken}}




### 5. 방장이 배틀 생성 -기대 : 202
POST http://localhost:8080/api/battles
Content-Type: application/json
Authorization: Bearer {{hostToken}}

{
  "title": "삭제 테스트 배틀",
  "videoId": "dQw4w9WgXcQ",
  "songTitle": "테스트곡",
  "channelTitle": "테스트채널",
  "thumbnailUrl": "https://example.com/thumb.jpg",
  "durationSec": 180
}

> {%
    client.global.set("battleId", response.body.battleId);
%}

### 5. 방장이 배틀 생성-기대 : 202
POST http://localhost:8080/api/battles
Content-Type: application/json
Authorization: Bearer {{hostToken}}

{
  "title": "삭제 테스트 배틀",
  "videoId": "dQw4w9WgXcQ",
  "songTitle": "테스트곡",
  "channelTitle": "테스트채널2",
  "thumbnailUrl": "https://example.com/thumb.jpg",
  "durationSec": 180
}

> {%
    client.global.set("battleId", response.body.battleId);
%}
### 5. 방장이 배틀 생성 -기대 : 202
POST http://localhost:8080/api/battles
Content-Type: application/json
Authorization: Bearer {{hostToken}}

{
  "title": "삭제 테스트 배틀",
  "videoId": "dQw4w9WgXcQ",
  "songTitle": "테스트곡",
  "channelTitle": "테스트채널3",
  "thumbnailUrl": "https://example.com/thumb.jpg",
  "durationSec": 180
}

> {%
    client.global.set("battleId", response.body.battleId);
%}
### 5. 방장이 배틀 생성 - 기대: 409
POST http://localhost:8080/api/battles
Content-Type: application/json
Authorization: Bearer {{hostToken}}

{
  "title": "삭제 테스트 배틀",
  "videoId": "dQw4w9WgXcQ",
  "songTitle": "테스트곡",
  "channelTitle": "테스트채널4",
  "thumbnailUrl": "https://example.com/thumb.jpg",
  "durationSec": 180
}

> {%
    client.global.set("battleId", response.body.battleId);
%}

