### 댓글 작성
POST http://localhost:8080/api/battles/1/comments
Authorization: Bearer {{token}}
Content-Type: application/json

{ "comment": "안녕하세요!" }

### 댓글 조회 (전체)
GET http://localhost:8080/api/battles/1/comments

### 댓글 조회 (특정 시각 이후)
GET http://localhost:8080/api/battles/1/comments?afterTime=2026-08-23T10:00:00